#!/usr/bin/env node
const fs = require('fs');
const repo = process.env.GITHUB_REPOSITORY;
const token = process.env.GITHUB_TOKEN;
if (!repo || !token) { console.error('GITHUB_REPOSITORY and GITHUB_TOKEN are required'); process.exit(1); }
const [owner, name] = repo.split('/');
const api = 'https://api.github.com';
const headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json', 'X-GitHub-Api-Version': '2022-11-28', 'User-Agent': 'fintimes-run-index' };
async function request(url) { const res = await fetch(url, { headers }); if (!res.ok) throw new Error(`${res.status} ${res.statusText}: ${(await res.text()).slice(0, 500)}`); return res.json(); }
function inferEdition(run) { const s = `${run.display_title || ''} ${run.name || ''}`.toLowerCase(); if (s.includes('morning')) return 'Morning Economy Brief'; if (s.includes('midday')) return 'Midday Market Explainer'; if (s.includes('market close') || s.includes('close')) return 'Market Close Explainer'; if (s.includes('evening')) return 'Evening Money Explained'; if (s.includes('weekly')) return 'Consolidated Weekly Wrap'; if (s.includes('corrected')) return '25 June Corrected Edition'; if (s.includes('studio')) return 'Studio Edition'; return run.display_title || run.name || 'Unknown edition'; }
function scheduledTime(edition, fallback) { return {'Morning Economy Brief':'Mon-Fri 08:00 IST / 02:30 UTC','Midday Market Explainer':'Mon-Fri 11:30 IST / 06:00 UTC','Market Close Explainer':'Mon-Fri 16:15 IST / 10:45 UTC','Evening Money Explained':'Mon-Fri 20:30 IST / 15:00 UTC','Consolidated Weekly Wrap':'Sunday 18:00 IST / 12:30 UTC'}[edition] || fallback; }
function failedStep(jobs) { for (const j of jobs) { for (const st of (j.steps || [])) if (['failure','cancelled'].includes(st.conclusion)) return `${j.name} / ${st.name}`; if (['failure','cancelled'].includes(j.conclusion)) return j.name; } return null; }
function youtubeResult(run, jobs, artifacts) { const text = [run.display_title, run.name, run.conclusion, ...jobs.map(j => `${j.name} ${j.conclusion}`), ...artifacts.map(a => a.name)].join(' ').toLowerCase(); const m = text.match(/(?:video[_ -]?id|youtube[_ -]?id)[:= _-]*([a-z0-9_-]{8,})/i); let result = 'pending'; if (run.status === 'completed') { if (/youtube.*skip|skipped.*youtube|upload.*skip/.test(text)) result = 'skipped'; else if (/youtube.*fail|upload.*fail/.test(text) || run.conclusion === 'failure') result = 'failed'; else if (/youtube|upload|published/.test(text) && run.conclusion === 'success') result = 'uploaded'; } const id = m ? m[1] : null; return {result, video_id:id, watch_url:id ? `https://www.youtube.com/watch?v=${id}` : null, actual_privacy_status:/private/.test(text)?'private':(/unlisted/.test(text)?'unlisted':(/public/.test(text)?'public':null)), thumbnail_result:/thumbnail.*fail/.test(text)?'failed':(/thumbnail/.test(text)?'produced_or_set':null), playlist_result:/playlist.*fail/.test(text)?'failed':(/playlist/.test(text)?'attempted':null)}; }
function visualChecks(run, artifactNames) { if (!/25 june|corrected|studio/i.test(`${run.display_title || ''} ${run.name || ''}`)) return null; return {required:true, source:'artifact-name scan; full frame verification requires rendered-frame artifacts', approved_intro_and_music_retained:/intro|music|approved/.test(artifactNames)?'evidence_found':'not_verified', modern_newsroom_visible:/newsroom|studio/.test(artifactNames)?'evidence_found':'not_verified', presenter_wide_long_shot:/wide|long-shot|long_shot/.test(artifactNames)?'evidence_found':'not_verified', split_screen_market_wall_visible:/split|market-wall|market_wall/.test(artifactNames)?'evidence_found':'not_verified', no_face_crop_or_zoom_returned:/crop|zoom/.test(artifactNames)?'needs_review':'not_verified'}; }
async function main() { const data = await request(`${api}/repos/${owner}/${name}/actions/runs?per_page=50`); const runs = (data.workflow_runs || []).filter(r => r.name !== 'Fintimes Run Index').filter(r => { const s = `${r.name || ''} ${r.display_title || ''} ${r.event || ''}`.toLowerCase(); return r.event === 'schedule' || /fintimes|production|youtube|studio|market|economy|weekly|brief|explainer|money/.test(s); }).slice(0,25); const editions = []; for (const run of runs) { const jobs = (await request(`${api}/repos/${owner}/${name}/actions/runs/${run.id}/jobs?per_page=100`)).jobs || []; const artifacts = (await request(`${api}/repos/${owner}/${name}/actions/runs/${run.id}/artifacts?per_page=100`)).artifacts || []; const names = artifacts.map(a=>a.name.toLowerCase()).join(' '); const ed = inferEdition(run); const yt = youtubeResult(run,jobs,artifacts); editions.push({edition:ed, scheduled_time:scheduledTime(ed,run.created_at), repository:repo, workflow_name:run.name, run_id:run.id, run_attempt:run.run_attempt, run_url:run.html_url, event:run.event, status:run.status, conclusion:run.conclusion, created_at:run.created_at, updated_at:run.updated_at, current_production_stage:run.status !== 'completed' ? run.status : (run.conclusion === 'failure' ? 'failed' : (run.conclusion === 'cancelled' ? 'cancelled' : (/youtube|upload|published|metadata/.test(names) ? 'publication complete or attempted' : (/video|render/.test(names) ? 'render complete' : run.conclusion)))), failed_step:failedStep(jobs), produced:{final_video:/video|final|mp4|render/.test(names), thumbnail:/thumbnail|thumb/.test(names), metadata:/metadata|youtube|description|tags|json/.test(names)}, youtube:yt, thumbnail_result:yt.thumbnail_result, playlist_result:yt.playlist_result, artifacts:artifacts.map(a=>({id:a.id,name:a.name,expired:a.expired,created_at:a.created_at,updated_at:a.updated_at})), visual_checks:visualChecks(run,names)}); } fs.mkdirSync('docs',{recursive:true}); const output = {generated_at:new Date().toISOString(), repository:repo, note:'Fetch this file to monitor latest Actions runs when direct run listing is unavailable.', editions}; fs.writeFileSync('docs/fintimes-run-index.json', JSON.stringify(output,null,2)+'\n'); fs.writeFileSync('docs/fintimes-run-index.md', '# Fintimes Run Index\n\nGenerated: '+output.generated_at+'\n\n| Edition | Workflow | Status | Stage | YouTube | Video | Failed step | Run |\n|---|---|---|---|---|---|---|---|\n'+editions.map(e=>`| ${e.edition} | ${e.workflow_name} | ${e.status}/${e.conclusion || ''} | ${e.current_production_stage} | ${e.youtube.result} | ${e.youtube.video_id || ''} | ${e.failed_step || ''} | [run](${e.run_url}) |`).join('\n')+'\n'); }
main().catch(err => { console.error(err); process.exit(1); });
